export interface GovernmentService {
  id: string;
  country: "IE" | "UAE" | "RW" | "IN" | "CA-US";
  countryName: string;
  lifeEvents: ("new-baby" | "job-loss" | "start-business")[];
  employment: ("employed" | "self-employed" | "unemployed" | "any")[];
  category: string;
  name: string;
  description: string;
  amount?: string;
  duration?: string;
  agency: string;
  agencyUrl?: string;
  processingTime: string;
  documents: string[];
  deadline: string;
  priority: "high" | "medium" | "low";
  tags: string[];
  weekToApply: 1 | 2 | 4 | 12;
}

export const services: GovernmentService[] = [
  // ═══════════════════ IRELAND — NEW BABY ═══════════════════════

  {
    id: "ie-maternity-benefit",
    country: "IE",
    countryName: "Ireland",
    lifeEvents: ["new-baby"],
    employment: ["employed"],
    category: "maternity",
    name: "Maternity Benefit",
    description:
      "Weekly payment for employed women taking maternity leave. You receive 26 weeks of paid leave, with an option for 16 further unpaid weeks.",
    amount: "€250/week",
    duration: "26 weeks (+ 16 weeks unpaid)",
    agency: "Department of Social Protection",
    agencyUrl: "https://www.gov.ie/en/service/apply-for-maternity-benefit/",
    processingTime: "4–6 weeks",
    documents: [
      "MB1 form (completed by your employer)",
      "MB2 form (completed by your doctor/midwife)",
      "PPS Number",
      "Bank account details (IBAN)",
    ],
    deadline: "Apply 6 weeks before your due date",
    priority: "high",
    tags: ["maternity", "leave", "income", "pregnancy"],
    weekToApply: 1,
  },

  {
    id: "ie-paternity-benefit",
    country: "IE",
    countryName: "Ireland",
    lifeEvents: ["new-baby"],
    employment: ["employed"],
    category: "maternity",
    name: "Paternity Benefit",
    description:
      "2-week paid leave for the other parent (father or non-birth parent) after a baby is born or adopted. Must be taken in one block within 26 weeks of birth.",
    amount: "€250/week",
    duration: "2 weeks",
    agency: "Department of Social Protection",
    agencyUrl: "https://www.gov.ie/en/service/apply-for-paternity-benefit/",
    processingTime: "2–4 weeks",
    documents: [
      "PB1 form (employer signature)",
      "Baby's birth certificate or expected due date",
      "PPS Number",
      "Bank details",
    ],
    deadline: "Apply before your paternity leave starts (within 26 weeks of birth)",
    priority: "high",
    tags: ["paternity", "father", "leave", "partner"],
    weekToApply: 1,
  },

  {
    id: "ie-parents-benefit",
    country: "IE",
    countryName: "Ireland",
    lifeEvents: ["new-baby"],
    employment: ["employed", "self-employed"],
    category: "maternity",
    name: "Parent's Benefit",
    description:
      "Each parent gets 9 weeks of paid leave in the first 2 years of a child's life. Parents can take this separately or together — it is on top of maternity and paternity leave.",
    amount: "€250/week",
    duration: "9 weeks per parent",
    agency: "Department of Social Protection",
    agencyUrl: "https://www.gov.ie/en/service/apply-for-parents-benefit/",
    processingTime: "4–6 weeks",
    documents: [
      "Parent's Benefit form",
      "Baby's PPS Number",
      "Birth certificate",
      "Employer confirmation (if employed)",
    ],
    deadline: "Must be taken within 2 years of birth",
    priority: "medium",
    tags: ["parental leave", "both parents", "flexible"],
    weekToApply: 2,
  },

  {
    id: "ie-child-benefit",
    country: "IE",
    countryName: "Ireland",
    lifeEvents: ["new-baby"],
    employment: ["any"],
    category: "child",
    name: "Child Benefit",
    description:
      "Monthly payment for each child under 16 (or under 18 in full-time education). Paid directly to the primary carer. Automatic once the baby is registered.",
    amount: "€140/month",
    duration: "Until age 16",
    agency: "Department of Social Protection",
    agencyUrl: "https://www.gov.ie/en/service/child-benefit/",
    processingTime: "6–8 weeks from birth registration",
    documents: [
      "Child's birth certificate",
      "Child's PPS Number (assigned at birth)",
      "Parent's PPS Number",
    ],
    deadline: "Apply within 12 months of birth (back-dated up to 12 months)",
    priority: "high",
    tags: ["monthly payment", "child", "family"],
    weekToApply: 1,
  },

  {
    id: "ie-maternity-infant-care",
    country: "IE",
    countryName: "Ireland",
    lifeEvents: ["new-baby"],
    employment: ["any"],
    category: "healthcare",
    name: "Maternity & Infant Care Scheme",
    description:
      "Free GP visits for the mother during pregnancy and for the baby's first 6 weeks. Covers all routine ante-natal and post-natal check-ups at your GP — no co-payment.",
    amount: "Free (est. €500+ in GP fees)",
    duration: "During pregnancy + 6 weeks post-birth",
    agency: "HSE (Health Service Executive)",
    agencyUrl: "https://www.hse.ie/eng/health/hl/pregnancy/combined-antenatal-care/",
    processingTime: "Immediate once enrolled with a participating GP",
    documents: [
      "GP referral form",
      "Maternity hospital booking confirmation",
    ],
    deadline: "Enrol with your GP as soon as pregnancy is confirmed",
    priority: "high",
    tags: ["free GP", "ante-natal", "healthcare", "pregnancy"],
    weekToApply: 1,
  },

  {
    id: "ie-public-health-nurse",
    country: "IE",
    countryName: "Ireland",
    lifeEvents: ["new-baby"],
    employment: ["any"],
    category: "healthcare",
    name: "Public Health Nurse Home Visit",
    description:
      "A Public Health Nurse visits your home within days of leaving hospital to check on you and your newborn. Ongoing follow-up visits are scheduled automatically by your local HSE.",
    amount: "Free",
    duration: "Multiple visits in first year",
    agency: "HSE Community Healthcare",
    processingTime: "Automatic — hospital notifies HSE",
    documents: ["None required — hospital notifies your local PHN"],
    deadline: "Automatically scheduled within 72 hours of hospital discharge",
    priority: "medium",
    tags: ["home visit", "nurse", "newborn check", "free"],
    weekToApply: 1,
  },

  {
    id: "ie-gp-visit-card-under8",
    country: "IE",
    countryName: "Ireland",
    lifeEvents: ["new-baby"],
    employment: ["any"],
    category: "healthcare",
    name: "GP Visit Card — Children Under 8",
    description:
      "All children under 8 are entitled to free GP visits (no means test). This saves approximately €600+ per year in GP fees. The card is linked to your child's PPS Number.",
    amount: "Free GP visits (est. €600/year)",
    duration: "Until age 8",
    agency: "HSE Primary Care",
    agencyUrl: "https://www.hse.ie/eng/services/list/1/schemes/mc/children/",
    processingTime: "2–4 weeks",
    documents: [
      "Child's PPS Number",
      "Birth certificate",
      "Parent/guardian proof of address",
    ],
    deadline: "Apply within 3 months of birth for earliest coverage",
    priority: "medium",
    tags: ["GP card", "free healthcare", "under 8", "children"],
    weekToApply: 2,
  },

  {
    id: "ie-ecce",
    country: "IE",
    countryName: "Ireland",
    lifeEvents: ["new-baby"],
    employment: ["any"],
    category: "childcare",
    name: "ECCE Free Pre-School Scheme",
    description:
      "Two years of free pre-school for children aged 2 years 8 months to 5 years 6 months. Worth approximately €5,000 per year — the State funds the childcare provider directly.",
    amount: "Free (est. €5,000/year)",
    duration: "Up to 2 school years",
    agency: "Department of Children, Equality, Disability",
    agencyUrl: "https://www.gov.ie/en/service/ecce-scheme/",
    processingTime: "Register before 1st February for September start",
    documents: [
      "Child's birth certificate",
      "Completed registration form with childcare provider",
    ],
    deadline: "Register before February for September of child's qualifying year",
    priority: "low",
    tags: ["childcare", "pre-school", "free", "ECCE"],
    weekToApply: 12,
  },

  // ── IE new-baby self-employed extras ───────────────────────────

  {
    id: "ie-maternity-benefit-se",
    country: "IE",
    countryName: "Ireland",
    lifeEvents: ["new-baby"],
    employment: ["self-employed"],
    category: "maternity",
    name: "Maternity Benefit (Self-Employed)",
    description:
      "Self-employed women can claim Maternity Benefit if they have paid sufficient Class S PRSI contributions. The rate and duration are the same as for employees.",
    amount: "€250/week",
    duration: "26 weeks",
    agency: "Department of Social Protection",
    agencyUrl: "https://www.gov.ie/en/service/apply-for-maternity-benefit/",
    processingTime: "4–6 weeks",
    documents: [
      "MB1 form (self-declaration for self-employed)",
      "MB2 form (doctor/midwife)",
      "PRSI contribution history",
      "Bank details",
    ],
    deadline: "Apply 6 weeks before due date",
    priority: "high",
    tags: ["maternity", "self-employed", "PRSI", "income"],
    weekToApply: 1,
  },

  {
    id: "ie-working-family-payment",
    country: "IE",
    countryName: "Ireland",
    lifeEvents: ["new-baby"],
    employment: ["employed", "self-employed"],
    category: "family",
    name: "Working Family Payment",
    description:
      "Weekly tax-free payment for families with children where at least one parent works 38+ hours per fortnight. Supplements low incomes — average payment is €143/week.",
    amount: "Up to €450/week (income dependent)",
    duration: "Renewed annually",
    agency: "Department of Social Protection",
    agencyUrl: "https://www.gov.ie/en/service/working-family-payment/",
    processingTime: "6–8 weeks",
    documents: [
      "WFP1 application form",
      "Recent payslips (last 3 months)",
      "Birth certificates for all children",
      "Employer letter confirming hours",
    ],
    deadline: "Apply when baby arrives (income assessed from next pay date)",
    priority: "medium",
    tags: ["working family", "low income", "supplement", "weekly"],
    weekToApply: 2,
  },

  // ═══════════════════ IRELAND — JOB LOSS ══════════════════════

  {
    id: "ie-jobseekers-benefit",
    country: "IE",
    countryName: "Ireland",
    lifeEvents: ["job-loss"],
    employment: ["unemployed"],
    category: "unemployment",
    name: "Jobseeker's Benefit",
    description:
      "Weekly payment for people who have lost their job and paid sufficient PRSI contributions. Apply on your FIRST day of unemployment — there is a 3-day waiting period before payments begin.",
    amount: "€232/week",
    duration: "9 months (or 6 months if under 2 years PRSI)",
    agency: "Department of Social Protection",
    agencyUrl: "https://www.gov.ie/en/service/jobseekers-benefit/",
    processingTime: "1–2 weeks",
    documents: [
      "PPS Number",
      "P45 from your last employer",
      "Evidence of seeking work (3 job applications per week)",
      "Bank account details",
    ],
    deadline: "Apply on Day 1 of unemployment — back-dating is limited to 6 days",
    priority: "high",
    tags: ["weekly payment", "unemployment", "immediate", "PRSI"],
    weekToApply: 1,
  },

  {
    id: "ie-jobseekers-allowance",
    country: "IE",
    countryName: "Ireland",
    lifeEvents: ["job-loss"],
    employment: ["unemployed"],
    category: "unemployment",
    name: "Jobseeker's Allowance",
    description:
      "Means-tested payment for people who have exhausted Jobseeker's Benefit or who have insufficient PRSI contributions. No PRSI requirement — income and assets are assessed.",
    amount: "Up to €232/week",
    duration: "Ongoing while unemployed and meeting criteria",
    agency: "Department of Social Protection",
    agencyUrl: "https://www.gov.ie/en/service/jobseekers-allowance/",
    processingTime: "2–4 weeks",
    documents: [
      "Means assessment form",
      "Bank statements (3 months)",
      "Proof of address",
      "Evidence of job-seeking",
    ],
    deadline: "Apply after Benefit is exhausted or if you don't qualify for Benefit",
    priority: "high",
    tags: ["means-tested", "fallback", "unemployment"],
    weekToApply: 1,
  },

  {
    id: "ie-back-to-education",
    country: "IE",
    countryName: "Ireland",
    lifeEvents: ["job-loss"],
    employment: ["unemployed"],
    category: "education",
    name: "Back to Education Allowance",
    description:
      "You can keep your Jobseeker's payment and return to full-time education. This covers second-level, third-level, and Post-Leaving Certificate (PLC) courses.",
    amount: "Up to €232/week (same as your Jobseeker's rate)",
    duration: "For duration of your approved course",
    agency: "Department of Social Protection",
    agencyUrl: "https://www.gov.ie/en/service/back-to-education-allowance/",
    processingTime: "4–6 weeks",
    documents: [
      "Letter of acceptance from course/college",
      "Proof of 9 months on Jobseeker's payment",
      "Course details and duration",
    ],
    deadline: "Apply before September course start (decisions take 4–6 weeks)",
    priority: "medium",
    tags: ["education", "reskill", "college", "allowance"],
    weekToApply: 4,
  },

  {
    id: "ie-back-to-work-enterprise",
    country: "IE",
    countryName: "Ireland",
    lifeEvents: ["job-loss", "start-business"],
    employment: ["unemployed"],
    category: "business",
    name: "Back to Work Enterprise Allowance",
    description:
      "Start a self-employed business while keeping a portion of your social welfare payment for 2 years. Year 1: 100% of payment. Year 2: 75% of payment.",
    amount: "100% of SW rate (yr 1) / 75% (yr 2)",
    duration: "2 years",
    agency: "Department of Social Protection",
    agencyUrl: "https://www.gov.ie/en/service/back-to-work-enterprise-allowance/",
    processingTime: "4–6 weeks",
    documents: [
      "Business plan",
      "12 months on qualifying SW payment",
      "DSP approval form",
    ],
    deadline: "Must be on qualifying payment for 12 months before applying",
    priority: "medium",
    tags: ["startup", "enterprise", "welfare", "self-employment"],
    weekToApply: 4,
  },

  {
    id: "ie-housing-assistance",
    country: "IE",
    countryName: "Ireland",
    lifeEvents: ["job-loss"],
    employment: ["unemployed"],
    category: "housing",
    name: "Housing Assistance Payment (HAP)",
    description:
      "If you are renting and your income drops, HAP covers part of your rent. Local Authority pays the landlord directly; you pay a differential rent based on income.",
    amount: "Varies by location (avg €1,200/month covered)",
    duration: "Ongoing while eligible",
    agency: "Local Authority (Council)",
    agencyUrl: "https://www.gov.ie/en/service/hap/",
    processingTime: "4–8 weeks",
    documents: [
      "Proof of income (or unemployment)",
      "Tenancy agreement",
      "Landlord details and PPSN",
      "HAP application form from your council",
    ],
    deadline: "Apply when income drops — no strict deadline but act quickly",
    priority: "medium",
    tags: ["rent", "housing", "council", "support"],
    weekToApply: 2,
  },

  {
    id: "ie-medical-card",
    country: "IE",
    countryName: "Ireland",
    lifeEvents: ["job-loss", "new-baby"],
    employment: ["unemployed"],
    category: "healthcare",
    name: "Medical Card",
    description:
      "Free GP visits, prescription drugs, dental, optical and hospital care for you and your family. Means-tested — losing your job often qualifies you automatically.",
    amount: "Free medical care (est. €2,000/year value)",
    duration: "Annual renewal",
    agency: "HSE Primary Care Reimbursement Service",
    agencyUrl: "https://www.hse.ie/eng/services/list/1/schemes/mc/",
    processingTime: "4 weeks",
    documents: [
      "Medical Card application form",
      "Proof of means (bank statements, SW payments)",
      "PPS Number",
    ],
    deadline: "Apply within 4 weeks of losing income",
    priority: "medium",
    tags: ["free healthcare", "GP", "prescription", "means-test"],
    weekToApply: 2,
  },

  {
    id: "ie-community-employment",
    country: "IE",
    countryName: "Ireland",
    lifeEvents: ["job-loss"],
    employment: ["unemployed"],
    category: "employment",
    name: "Community Employment Scheme",
    description:
      "Part-time work (19.5 hours/week) in a community setting, with training. Get work experience while keeping your social welfare payment plus a top-up of €22.50/week.",
    amount: "€232 + €22.50/week top-up",
    duration: "1–3 years depending on scheme",
    agency: "Department of Social Protection / Local CE Sponsors",
    agencyUrl: "https://www.gov.ie/en/service/community-employment/",
    processingTime: "2–4 weeks after placement found",
    documents: [
      "CE placement approval from DSP",
      "12+ months on qualifying payment",
    ],
    deadline: "No fixed deadline — apply through your local Intreo office",
    priority: "low",
    tags: ["community work", "training", "experience"],
    weekToApply: 12,
  },

  // ═══════════════════ IRELAND — START BUSINESS ═════════════════

  {
    id: "ie-new-enterprise-allowance",
    country: "IE",
    countryName: "Ireland",
    lifeEvents: ["start-business"],
    employment: ["unemployed"],
    category: "business",
    name: "New Enterprise Allowance (NEA)",
    description:
      "Up to €11,000 over 2 years to help you start a viable business. Includes a business mentor, access to a €25,000 start-up loan, and the allowance is paid weekly.",
    amount: "€11,000 over 2 years (€198/week yr 1, €99/week yr 2)",
    duration: "2 years",
    agency: "Department of Social Protection",
    agencyUrl: "https://www.gov.ie/en/service/new-enterprise-allowance/",
    processingTime: "6–8 weeks (includes mentor sign-off)",
    documents: [
      "Business plan (approved by DSP mentor)",
      "Current on qualifying SW payment",
      "Evidence of viable business concept",
    ],
    deadline: "Must be on qualifying SW payment — apply before starting the business",
    priority: "high",
    tags: ["startup", "grant", "allowance", "mentor", "loan"],
    weekToApply: 1,
  },

  {
    id: "ie-leo-grant",
    country: "IE",
    countryName: "Ireland",
    lifeEvents: ["start-business"],
    employment: ["any"],
    category: "business",
    name: "Local Enterprise Office (LEO) Priming Grant",
    description:
      "Capital grant for new businesses in their first 18 months. Covers equipment, premises, marketing, and staff costs. LEO also provides free mentoring and training.",
    amount: "Up to €150,000 (typically €10,000–€50,000)",
    duration: "One-time grant",
    agency: "Local Enterprise Office (your county)",
    agencyUrl: "https://www.localenterprise.ie/",
    processingTime: "8–12 weeks",
    documents: [
      "Detailed business plan",
      "3-year financial projections",
      "CV and experience summary",
      "Quotes for proposed expenditure",
    ],
    deadline: "Apply before spending the money — grants are paid in arrears",
    priority: "high",
    tags: ["grant", "capital", "LEO", "startup"],
    weekToApply: 2,
  },

  {
    id: "ie-cro-registration",
    country: "IE",
    countryName: "Ireland",
    lifeEvents: ["start-business"],
    employment: ["any"],
    category: "business",
    name: "CRO Company Registration",
    description:
      "Register your Limited Company (LTD) or Designated Activity Company (DAC) with the Companies Registration Office. Must be done before trading as a company.",
    amount: "€50 (online) / €100 (paper)",
    duration: "Once-off registration",
    agency: "Companies Registration Office",
    agencyUrl: "https://www.cro.ie/",
    processingTime: "3–5 working days (online)",
    documents: [
      "Form A1 (incorporation form)",
      "Constitution of the company",
      "Director and shareholder details",
      "Registered office address in Ireland",
    ],
    deadline: "Register before issuing invoices as a company",
    priority: "high",
    tags: ["company", "incorporation", "CRO", "legal"],
    weekToApply: 1,
  },

  {
    id: "ie-revenue-registration",
    country: "IE",
    countryName: "Ireland",
    lifeEvents: ["start-business"],
    employment: ["any"],
    category: "business",
    name: "Revenue Tax Registration",
    description:
      "Register for tax (Income Tax or Corporation Tax), VAT (if turnover > €37,500 for services / €75,000 for goods), and PAYE if you plan to have employees.",
    amount: "Free",
    duration: "Ongoing compliance",
    agency: "Revenue Commissioners",
    agencyUrl: "https://www.revenue.ie/en/online-services/services/register-for-taxes/",
    processingTime: "1–2 weeks",
    documents: [
      "PPS Number (sole trader) or Company CRO number",
      "Business activity details",
      "Expected turnover",
    ],
    deadline: "Within 30 days of commencing business activity",
    priority: "high",
    tags: ["tax", "VAT", "revenue", "compliance"],
    weekToApply: 1,
  },

  {
    id: "ie-ei-competitive-start",
    country: "IE",
    countryName: "Ireland",
    lifeEvents: ["start-business"],
    employment: ["any"],
    category: "business",
    name: "Enterprise Ireland Competitive Start Fund",
    description:
      "Equity investment of up to €50,000 for high-potential start-up companies. Enterprise Ireland takes a small equity stake in return. Focuses on export-led businesses.",
    amount: "Up to €50,000 equity investment",
    duration: "One-time investment",
    agency: "Enterprise Ireland",
    agencyUrl: "https://www.enterprise-ireland.com/en/funding-supports/company/start-up-refundable-aid/",
    processingTime: "8–12 weeks (competitive process)",
    documents: [
      "Online application",
      "Business plan with export potential",
      "Pitch deck",
      "Financial projections (3 years)",
      "Team CVs",
    ],
    deadline: "Rolling competitions — check Enterprise Ireland website for next round",
    priority: "medium",
    tags: ["equity", "investment", "high-potential", "export"],
    weekToApply: 4,
  },

  {
    id: "ie-microfinance",
    country: "IE",
    countryName: "Ireland",
    lifeEvents: ["start-business"],
    employment: ["any"],
    category: "finance",
    name: "Microfinance Ireland Loan",
    description:
      "Loans of €2,000 to €25,000 for businesses that can't get bank finance. Lower interest rates than banks. Suitable for businesses under 2 years old or without a credit history.",
    amount: "€2,000 to €25,000",
    duration: "Up to 7 years",
    agency: "Microfinance Ireland",
    agencyUrl: "https://microfinanceireland.ie/",
    processingTime: "2–4 weeks",
    documents: [
      "Business plan",
      "Cash flow projections",
      "Evidence of bank refusal (if applicable)",
      "Business registration",
    ],
    deadline: "No fixed deadline — apply when ready",
    priority: "medium",
    tags: ["loan", "finance", "startup", "SME"],
    weekToApply: 4,
  },

  {
    id: "ie-startup-tax-relief",
    country: "IE",
    countryName: "Ireland",
    lifeEvents: ["start-business"],
    employment: ["any"],
    category: "tax",
    name: "Start-Up Relief for Entrepreneurs (SURE)",
    description:
      "If you were previously PAYE employed, you can reclaim up to €100,000 of income tax you paid in the past 6 years by investing it in your new company. Powerful tax incentive.",
    amount: "Up to €100,000 tax refund",
    duration: "One-time claim",
    agency: "Revenue Commissioners",
    agencyUrl: "https://www.revenue.ie/en/tax-professionals/tdm/income-tax-capital-gains-tax-corporation-tax/part-16/16-00-03.pdf",
    processingTime: "4–8 weeks",
    documents: [
      "SURE claim form",
      "Evidence of previous PAYE employment",
      "Investment confirmation in your company",
      "Company share certificate",
    ],
    deadline: "Claim within 4 years of investing — file with your tax return",
    priority: "medium",
    tags: ["tax relief", "SURE", "investment", "refund"],
    weekToApply: 4,
  },

  // ═══════════════════ UAE — NEW BABY ════════════════════════════

  {
    id: "uae-parental-leave",
    country: "UAE",
    countryName: "UAE",
    lifeEvents: ["new-baby"],
    employment: ["employed"],
    category: "maternity",
    name: "Parental Leave (UAE Labour Law)",
    description:
      "Fathers in the private sector are entitled to 5 days of paid paternity leave within 6 months of the baby's birth. Maternity leave for mothers is 60 days (full pay for 45 days, half pay for 15 days).",
    amount: "Paid (maternity: full salary 45 days + 50% for 15 days)",
    duration: "Maternity: 60 days | Paternity: 5 days",
    agency: "Ministry of Human Resources & Emiratisation (MOHRE)",
    agencyUrl: "https://www.mohre.gov.ae/",
    processingTime: "HR department processes within 5 days",
    documents: [
      "Birth certificate",
      "Emirates ID",
      "HR notification form",
    ],
    deadline: "Notify employer within 1 week of birth",
    priority: "high",
    tags: ["maternity leave", "paternity leave", "labour law", "paid"],
    weekToApply: 1,
  },

  {
    id: "uae-birth-registration",
    country: "UAE",
    countryName: "UAE",
    lifeEvents: ["new-baby"],
    employment: ["any"],
    category: "registration",
    name: "TAMM Birth Registration",
    description:
      "All births in the UAE must be registered within 30 days at a government hospital or via the TAMM app. A birth certificate and baby's Emirates ID are issued — required for all future services.",
    amount: "Free (within 30 days) / AED 200 (after 30 days)",
    duration: "Once-off",
    agency: "Department of Health / TAMM (Abu Dhabi) / DHA (Dubai)",
    agencyUrl: "https://www.tamm.abudhabi/",
    processingTime: "Same day at hospital or 1–2 days via TAMM app",
    documents: [
      "Hospital birth notification",
      "Both parents' Emirates ID",
      "Marriage certificate",
      "Passport copies of both parents",
    ],
    deadline: "Within 30 days of birth (mandatory by law)",
    priority: "high",
    tags: ["registration", "birth certificate", "mandatory", "TAMM"],
    weekToApply: 1,
  },

  {
    id: "uae-health-insurance-newborn",
    country: "UAE",
    countryName: "UAE",
    lifeEvents: ["new-baby"],
    employment: ["any"],
    category: "healthcare",
    name: "Newborn Health Insurance Coverage",
    description:
      "In Abu Dhabi and Dubai, employers are legally required to add newborns to their health insurance within 30 days. Failure to do so leaves the baby uninsured and can incur fines.",
    amount: "Covered under employer policy",
    duration: "From birth onwards",
    agency: "Your employer's HR department + DAMAN or DHA network",
    processingTime: "5–10 working days",
    documents: [
      "Birth certificate",
      "Baby's Emirates ID (once issued)",
      "HR enrollment form",
    ],
    deadline: "Add to policy within 30 days of birth",
    priority: "high",
    tags: ["insurance", "health coverage", "employer", "mandatory"],
    weekToApply: 1,
  },

  {
    id: "uae-abu-dhabi-child-allowance",
    country: "UAE",
    countryName: "UAE",
    lifeEvents: ["new-baby"],
    employment: ["employed"],
    category: "child",
    name: "Abu Dhabi Children's Allowance (Nationals)",
    description:
      "UAE nationals working in the government sector receive a monthly children's allowance. Private sector nationals may also be eligible through certain schemes.",
    amount: "AED 1,000/month per child",
    duration: "Until child is 18 (or 23 if in university)",
    agency: "Abu Dhabi Human Resources Authority (ADHRÁ)",
    agencyUrl: "https://www.adhrá.gov.ae/",
    processingTime: "4–6 weeks",
    documents: [
      "Birth certificate",
      "Family book (Khulasat Al-Qaid)",
      "Emirates ID",
      "Employment contract",
    ],
    deadline: "Apply within 3 months of birth",
    priority: "medium",
    tags: ["nationals", "allowance", "monthly", "Abu Dhabi"],
    weekToApply: 2,
  },

  {
    id: "uae-maternity-insurance",
    country: "UAE",
    countryName: "UAE",
    lifeEvents: ["new-baby"],
    employment: ["any"],
    category: "healthcare",
    name: "Maternity Health Package",
    description:
      "Private insurance plans typically cover maternity costs between AED 10,000–AED 50,000. Ensure your health insurance includes maternity coverage and that your newborn is enrolled at birth.",
    amount: "Covered (up to AED 50,000 depending on plan)",
    duration: "Delivery + post-natal care",
    agency: "Your health insurer (DAMAN, AXA, MetLife, etc.)",
    processingTime: "Pre-authorisation within 48 hours for planned births",
    documents: [
      "Insurance card",
      "Pre-authorisation form for planned C-section",
      "Referral letter if required",
    ],
    deadline: "Pre-authorise planned delivery 2 weeks in advance",
    priority: "medium",
    tags: ["maternity", "insurance", "hospital", "delivery"],
    weekToApply: 1,
  },

  // ═══════════════════ UAE — JOB LOSS ════════════════════════════

  {
    id: "uae-iloe",
    country: "UAE",
    countryName: "UAE",
    lifeEvents: ["job-loss"],
    employment: ["unemployed"],
    category: "unemployment",
    name: "ILOE — Involuntary Loss of Employment Insurance",
    description:
      "UAE's unemployment insurance scheme. Workers pay a small monthly premium (AED 5–10) and receive 60% of their last salary for up to 3 months if involuntarily made redundant.",
    amount: "60% of last salary for 3 months",
    duration: "Up to 3 months",
    agency: "Ministry of Human Resources (MOHRE)",
    agencyUrl: "https://iloe.mohre.gov.ae/",
    processingTime: "2–3 weeks after claim submission",
    documents: [
      "Emirates ID",
      "Termination letter from employer",
      "Bank account details",
      "ILOE scheme subscription proof",
    ],
    deadline: "File claim within 30 days of unemployment",
    priority: "high",
    tags: ["ILOE", "unemployment insurance", "income replacement", "MOHRE"],
    weekToApply: 1,
  },

  {
    id: "uae-end-of-service",
    country: "UAE",
    countryName: "UAE",
    lifeEvents: ["job-loss"],
    employment: ["unemployed"],
    category: "employment",
    name: "End-of-Service Gratuity",
    description:
      "Employees with 1+ year of service are entitled to gratuity pay: 21 days of basic salary per year for the first 5 years, then 30 days per year after 5 years.",
    amount: "21–30 days basic salary per year of service",
    duration: "One-time payment",
    agency: "Your Employer (via Ministry of Labour if disputed)",
    agencyUrl: "https://www.mohre.gov.ae/",
    processingTime: "Must be paid within 14 days of last working day",
    documents: [
      "Employment contract",
      "Final settlement letter",
      "Bank details for transfer",
    ],
    deadline: "Employer must pay within 14 days — raise complaint if delayed",
    priority: "high",
    tags: ["gratuity", "end of service", "entitlement", "mandatory"],
    weekToApply: 1,
  },

  {
    id: "uae-visa-grace-period",
    country: "UAE",
    countryName: "UAE",
    lifeEvents: ["job-loss"],
    employment: ["unemployed"],
    category: "immigration",
    name: "Employment Visa Grace Period",
    description:
      "After losing your job, your employment visa remains valid for 60 days (recently extended to 180 days in some Emirates). Use this time to find a new job or arrange other visa status.",
    amount: "Free (no action needed)",
    duration: "60–180 days depending on visa type",
    agency: "ICA — Federal Authority for Identity, Citizenship, Customs",
    agencyUrl: "https://www.ica.gov.ae/",
    processingTime: "Automatic upon termination",
    documents: [
      "Emirates ID",
      "Cancellation letter from employer",
    ],
    deadline: "Leave UAE or change visa status before grace period expires",
    priority: "high",
    tags: ["visa", "grace period", "immigration", "residency"],
    weekToApply: 1,
  },

  {
    id: "uae-mohre-job-portal",
    country: "UAE",
    countryName: "UAE",
    lifeEvents: ["job-loss"],
    employment: ["unemployed"],
    category: "employment",
    name: "Ministry of HR Job Portal",
    description:
      "Register on the MOHRE job-seeker portal to access thousands of vacancies, recruitment agencies, and the Emiratisation program. Free for all workers in UAE.",
    amount: "Free",
    duration: "Until you find employment",
    agency: "Ministry of Human Resources & Emiratisation",
    agencyUrl: "https://eservices.mohre.gov.ae/",
    processingTime: "Registration complete within 24 hours",
    documents: [
      "Emirates ID",
      "Updated CV",
      "Professional qualifications (if relevant)",
    ],
    deadline: "Register immediately after job loss",
    priority: "medium",
    tags: ["job search", "portal", "MOHRE", "employment"],
    weekToApply: 1,
  },

  // ═══════════════════ UAE — START BUSINESS ══════════════════════

  {
    id: "uae-ded-trade-license",
    country: "UAE",
    countryName: "UAE",
    lifeEvents: ["start-business"],
    employment: ["any"],
    category: "business",
    name: "Dubai DED Trade License",
    description:
      "The primary business license for operating in mainland Dubai. Covers commercial, professional, and industrial activities. Required before legally conducting any business activity.",
    amount: "From AED 5,000/year (varies by activity)",
    duration: "Annual renewal",
    agency: "Department of Economy and Tourism (DET/DED), Dubai",
    agencyUrl: "https://www.ded.ae/",
    processingTime: "3–7 working days",
    documents: [
      "Passport copy of all shareholders",
      "Emirates ID (if resident)",
      "Business activity details",
      "Registered office / NOC from landlord",
      "Memorandum of Association (for companies)",
    ],
    deadline: "Before starting any commercial activity",
    priority: "high",
    tags: ["trade license", "DED", "Dubai", "mainland"],
    weekToApply: 1,
  },

  {
    id: "uae-free-zone",
    country: "UAE",
    countryName: "UAE",
    lifeEvents: ["start-business"],
    employment: ["any"],
    category: "business",
    name: "Free Zone Company Setup",
    description:
      "100% foreign ownership, no corporate tax (on applicable activities), and full profit repatriation. Major free zones: DIFC, DMCC, ADGM, Meydan. Best for international/digital businesses.",
    amount: "From AED 10,000/year (varies by free zone and activity)",
    duration: "Annual renewal",
    agency: "Respective Free Zone Authority (DMCC, DIFC, ADGM, etc.)",
    agencyUrl: "https://www.dmcc.ae/",
    processingTime: "1–2 weeks",
    documents: [
      "Passport copies",
      "Business plan / activity description",
      "Bank reference letter",
      "CV / professional background",
    ],
    deadline: "Before commencing business operations",
    priority: "high",
    tags: ["free zone", "100% ownership", "foreign", "no tax"],
    weekToApply: 1,
  },

  {
    id: "uae-khalifa-fund",
    country: "UAE",
    countryName: "UAE",
    lifeEvents: ["start-business"],
    employment: ["any"],
    category: "finance",
    name: "Khalifa Fund for Entrepreneurship",
    description:
      "UAE nationals can access financing from AED 50,000 to AED 3 million. Non-nationals in Abu Dhabi can access Khalifa Fund's SME financing for businesses with 51% UAE national ownership.",
    amount: "AED 50,000 to AED 3,000,000",
    duration: "Up to 10 years repayment",
    agency: "Khalifa Fund for Enterprise Development",
    agencyUrl: "https://www.khalifafund.ae/",
    processingTime: "4–8 weeks",
    documents: [
      "Business plan",
      "Financial projections",
      "Emirates ID",
      "Business license (or application)",
      "Bank statements (6 months)",
    ],
    deadline: "No fixed deadline — rolling applications",
    priority: "medium",
    tags: ["loan", "funding", "nationals", "SME"],
    weekToApply: 4,
  },

  {
    id: "uae-edb-sme-loan",
    country: "UAE",
    countryName: "UAE",
    lifeEvents: ["start-business"],
    employment: ["any"],
    category: "finance",
    name: "Emirates Development Bank SME Loan",
    description:
      "Low-interest financing for UAE SMEs in priority sectors (food security, tech, healthcare, manufacturing). Loans from AED 50,000 to AED 50 million.",
    amount: "AED 50,000 to AED 50,000,000",
    duration: "Up to 15 years",
    agency: "Emirates Development Bank",
    agencyUrl: "https://www.edb.gov.ae/",
    processingTime: "4–6 weeks",
    documents: [
      "Audited financial statements",
      "Business plan",
      "Trade license",
      "Emirates ID",
      "MOA / shareholder agreement",
    ],
    deadline: "Apply anytime — rolling basis",
    priority: "medium",
    tags: ["loan", "EDB", "SME", "priority sectors"],
    weekToApply: 4,
  },

  {
    id: "uae-uae-pass",
    country: "UAE",
    countryName: "UAE",
    lifeEvents: ["start-business"],
    employment: ["any"],
    category: "business",
    name: "UAE PASS — Government eServices Registration",
    description:
      "A single digital identity for all UAE government services. Required for MOHRE employee registration, ICA visas, and most online government transactions. Free to set up.",
    amount: "Free",
    duration: "Permanent",
    agency: "Smart Dubai / UAE Digital Authority",
    agencyUrl: "https://www.uaepass.ae/",
    processingTime: "15 minutes",
    documents: [
      "Emirates ID",
      "Selfie for face verification",
      "Mobile number",
    ],
    deadline: "Set up before applying for any government business services",
    priority: "high",
    tags: ["digital identity", "eServices", "government portal"],
    weekToApply: 1,
  },

  // ═══════════════════ RWANDA — NEW BABY ════════════════════════

  {
    id: "rw-maternity-leave",
    country: "RW",
    countryName: "Rwanda",
    lifeEvents: ["new-baby"],
    employment: ["employed"],
    category: "maternity",
    name: "Maternity Leave — 100% Employer Paid",
    description:
      "Rwandan labour law mandates 84 days (12 weeks) of maternity leave at 100% salary, paid by the employer. Fathers are entitled to 4 days paid leave within 7 days of birth.",
    amount: "100% salary for 84 days",
    duration: "84 days maternity / 4 days paternity",
    agency: "Rwanda Labour Board / Your Employer",
    agencyUrl: "https://www.alc.gov.rw/",
    processingTime: "HR processes within your notice period",
    documents: [
      "Letter from employer acknowledging leave",
      "Birth notification from hospital",
      "Employee contract",
    ],
    deadline: "Notify employer 2 weeks before due date",
    priority: "high",
    tags: ["maternity leave", "paid leave", "labour law", "Rwanda"],
    weekToApply: 1,
  },

  {
    id: "rw-birth-registration",
    country: "RW",
    countryName: "Rwanda",
    lifeEvents: ["new-baby"],
    employment: ["any"],
    category: "registration",
    name: "Irembo Birth Registration",
    description:
      "All births must be registered within 30 days via Irembo (Rwanda's e-government portal) or at a district office. Free of charge. Generates the national ID foundation for the child.",
    amount: "Free",
    duration: "One-time",
    agency: "National Civil Registration Authority (NCRA) via Irembo",
    agencyUrl: "https://irembo.gov.rw/",
    processingTime: "Same day at hospital or 1–2 days online",
    documents: [
      "Hospital birth notification",
      "Both parents' National IDs",
      "Completed birth registration form",
    ],
    deadline: "Within 30 days of birth (legal requirement)",
    priority: "high",
    tags: ["registration", "birth certificate", "Irembo", "mandatory"],
    weekToApply: 1,
  },

  {
    id: "rw-mutuelle-de-sante",
    country: "RW",
    countryName: "Rwanda",
    lifeEvents: ["new-baby"],
    employment: ["any"],
    category: "healthcare",
    name: "Mutuelle de Santé (Community Health Insurance)",
    description:
      "Rwanda's community-based health insurance scheme. Cover newborn immediately by adding them to the family policy. Covers 90%+ of healthcare costs at accredited facilities.",
    amount: "RWF 3,000–7,500/person/year (income-based premium)",
    duration: "Annual renewal",
    agency: "Rwanda Social Security Board (RSSB)",
    agencyUrl: "https://www.rssb.rw/",
    processingTime: "Enrol at your local health centre or sector office",
    documents: [
      "Birth certificate",
      "Family ID card",
      "Membership payment receipt",
    ],
    deadline: "Add baby within 30 days of birth — late enrollment may require waiting period",
    priority: "high",
    tags: ["health insurance", "Mutuelle", "free healthcare", "Rwanda"],
    weekToApply: 1,
  },

  {
    id: "rw-vup",
    country: "RW",
    countryName: "Rwanda",
    lifeEvents: ["new-baby"],
    employment: ["unemployed"],
    category: "social",
    name: "VUP — Vision 2020 Umurenge Social Protection",
    description:
      "For the most vulnerable households: direct support transfers (up to RWF 28,000/month), public works employment, and financial services linkages. Applied via your local sector office.",
    amount: "Up to RWF 28,000/month",
    duration: "Ongoing while eligible",
    agency: "Local Administrative Entities Development Agency (LODA)",
    agencyUrl: "https://www.loda.gov.rw/",
    processingTime: "4–8 weeks (household assessment required)",
    documents: [
      "National ID",
      "Proof of household vulnerability",
      "Application at Sector Office",
    ],
    deadline: "Apply at your local Sector Office — no fixed deadline",
    priority: "medium",
    tags: ["social protection", "VUP", "low income", "transfer"],
    weekToApply: 4,
  },

  // ═══════════════════ RWANDA — JOB LOSS ════════════════════════

  {
    id: "rw-rssb-social-security",
    country: "RW",
    countryName: "Rwanda",
    lifeEvents: ["job-loss"],
    employment: ["unemployed"],
    category: "unemployment",
    name: "RSSB Social Security Claim",
    description:
      "If you contributed to Rwanda Social Security Board (RSSB), you may be eligible to claim your pension or occupational hazard benefits. Access your contributions via the RSSB portal.",
    amount: "Dependent on contributions",
    duration: "One-time or ongoing pension",
    agency: "Rwanda Social Security Board (RSSB)",
    agencyUrl: "https://www.rssb.rw/",
    processingTime: "4–6 weeks",
    documents: [
      "National ID",
      "RSSB member number",
      "Employer confirmation of contributions",
    ],
    deadline: "Claim within 12 months of leaving employment",
    priority: "high",
    tags: ["social security", "RSSB", "pension", "contributions"],
    weekToApply: 1,
  },

  {
    id: "rw-wda-skills",
    country: "RW",
    countryName: "Rwanda",
    lifeEvents: ["job-loss"],
    employment: ["unemployed"],
    category: "education",
    name: "WDA Skills Development Programs",
    description:
      "The Workforce Development Authority provides free and subsidised vocational training. Covers ICT, construction, hospitality, agriculture, and more — courses from 3 months to 2 years.",
    amount: "Free to subsidised (RWF 0–30,000/term)",
    duration: "3 months to 2 years",
    agency: "Workforce Development Authority (WDA)",
    agencyUrl: "https://www.wda.gov.rw/",
    processingTime: "Intake is per term — register 4 weeks before term starts",
    documents: [
      "National ID",
      "Education certificates",
      "Application form",
    ],
    deadline: "Register before each term intake — check WDA website for dates",
    priority: "medium",
    tags: ["skills", "training", "vocational", "WDA"],
    weekToApply: 4,
  },

  {
    id: "rw-employment-services",
    country: "RW",
    countryName: "Rwanda",
    lifeEvents: ["job-loss"],
    employment: ["unemployed"],
    category: "employment",
    name: "Public Employment Services Centre",
    description:
      "Register at your nearest Employment Services Centre for job matching, CV assistance, and career counselling. RDB also hosts an online job portal at Akazi.gov.rw.",
    amount: "Free",
    duration: "Until employment found",
    agency: "Rwanda Development Board (RDB) Employment Services",
    agencyUrl: "https://www.akazi.gov.rw/",
    processingTime: "Same-day registration",
    documents: [
      "National ID",
      "CV / work history",
    ],
    deadline: "Register within first week of unemployment",
    priority: "medium",
    tags: ["job centre", "employment", "career", "free"],
    weekToApply: 1,
  },

  // ═══════════════════ RWANDA — START BUSINESS ══════════════════

  {
    id: "rw-irembo-business-reg",
    country: "RW",
    countryName: "Rwanda",
    lifeEvents: ["start-business"],
    employment: ["any"],
    category: "business",
    name: "Irembo Business Registration",
    description:
      "Rwanda's world-famous single-window company registration. Register your business entirely online in under 24 hours. One of the fastest in Africa — costs as little as RWF 5,000.",
    amount: "RWF 5,000–20,000 depending on type",
    duration: "One-time registration (annual renewal of trading license)",
    agency: "Rwanda Development Board (RDB) via Irembo",
    agencyUrl: "https://irembo.gov.rw/",
    processingTime: "4–24 hours",
    documents: [
      "National ID or Passport",
      "Business name (check availability on portal)",
      "Business activity description",
      "Shareholder details",
    ],
    deadline: "Before starting business operations",
    priority: "high",
    tags: ["registration", "company", "Irembo", "fast", "online"],
    weekToApply: 1,
  },

  {
    id: "rw-rra-tax-registration",
    country: "RW",
    countryName: "Rwanda",
    lifeEvents: ["start-business"],
    employment: ["any"],
    category: "tax",
    name: "RRA Tax Registration (TIN)",
    description:
      "Register for a Taxpayer Identification Number (TIN) with Rwanda Revenue Authority. Required for all businesses. VAT registration is compulsory above RWF 20M annual turnover.",
    amount: "Free",
    duration: "Permanent",
    agency: "Rwanda Revenue Authority (RRA)",
    agencyUrl: "https://www.rra.gov.rw/",
    processingTime: "1–2 days",
    documents: [
      "Business registration certificate",
      "National ID of directors",
    ],
    deadline: "Within 30 days of business registration",
    priority: "high",
    tags: ["tax", "TIN", "RRA", "VAT", "compliance"],
    weekToApply: 1,
  },

  {
    id: "rw-bdf-guarantee",
    country: "RW",
    countryName: "Rwanda",
    lifeEvents: ["start-business"],
    employment: ["any"],
    category: "finance",
    name: "BDF SME Loan Guarantee",
    description:
      "The Business Development Fund provides loan guarantees of up to 75% of your loan amount, making it easier to access bank financing. Also provides direct financing for youth entrepreneurs.",
    amount: "Guarantees on loans up to RWF 50,000,000",
    duration: "Duration of the underlying loan",
    agency: "Business Development Fund (BDF)",
    agencyUrl: "https://www.bdf.rw/",
    processingTime: "4–8 weeks",
    documents: [
      "Business plan",
      "Business registration",
      "Financial statements or projections",
      "Collateral details",
    ],
    deadline: "Apply before approaching the bank",
    priority: "medium",
    tags: ["loan guarantee", "BDF", "SME", "finance"],
    weekToApply: 4,
  },

  {
    id: "rw-rdb-investment-cert",
    country: "RW",
    countryName: "Rwanda",
    lifeEvents: ["start-business"],
    employment: ["any"],
    category: "business",
    name: "RDB Investment Certificate",
    description:
      "For investments above $250,000, an RDB Investment Certificate unlocks tax holidays, import duty exemptions, and expatriate work permit facilitation. Key for scaling businesses.",
    amount: "Free (unlocks tax incentives worth up to 35% of investment)",
    duration: "5–7 year tax holiday",
    agency: "Rwanda Development Board (RDB)",
    agencyUrl: "https://www.rdb.rw/",
    processingTime: "2–4 weeks",
    documents: [
      "Investment proposal",
      "Financial projections",
      "Company registration",
      "Evidence of minimum investment",
    ],
    deadline: "Apply before commencing operations to maximise tax benefit period",
    priority: "medium",
    tags: ["investment", "tax holiday", "RDB", "certificate"],
    weekToApply: 4,
  },

  {
    id: "rw-africa-free-trade",
    country: "RW",
    countryName: "Rwanda",
    lifeEvents: ["start-business"],
    employment: ["any"],
    category: "trade",
    name: "AfCFTA Market Access Support",
    description:
      "Rwanda is a member of the African Continental Free Trade Area. Registered businesses can access preferential tariffs across 55 African countries. RDB provides onboarding support.",
    amount: "Free market access support",
    duration: "Ongoing",
    agency: "Rwanda Development Board / National Industrial Research and Development Agency",
    agencyUrl: "https://www.rdb.rw/doing-business/trade/",
    processingTime: "2–4 weeks onboarding",
    documents: [
      "Business registration",
      "Product/service export readiness assessment",
      "Certificate of Origin eligibility",
    ],
    deadline: "No deadline — apply when export-ready",
    priority: "low",
    tags: ["export", "Africa", "trade", "AfCFTA"],
    weekToApply: 12,
  },

  // ═══════════════════ INDIA — NEW BABY ═══════════════════════

  {
    id: "in-maternity-benefit",
    country: "IN",
    countryName: "India",
    lifeEvents: ["new-baby"],
    employment: ["employed"],
    category: "maternity",
    name: "Maternity Benefit",
    agency: "Ministry of Labour & Employment / ESI Corporation",
    description: "Paid maternity leave for women employed in establishments with 10+ workers",
    amount: "Full average daily wage for 26 weeks",
    duration: "26 weeks (first 2 children), 12 weeks thereafter",
    processingTime: "2–4 weeks",
    documents: [
      "ESIC card",
      "Pregnancy certificate from doctor",
      "Form 23 / ESIC maternity claim form",
      "Bank account details",
    ],
    deadline: "Apply before delivery or within 30 days after",
    priority: "high",
    tags: ["ESIC", "maternity", "paid leave"],
    weekToApply: 1,
  },

  {
    id: "in-pmmvy",
    country: "IN",
    countryName: "India",
    lifeEvents: ["new-baby"],
    employment: ["employed", "self-employed", "unemployed"],
    category: "maternity",
    name: "PMMVY — Maternity Benefit Programme",
    agency: "Ministry of Women & Child Development",
    description: "Cash incentive for first living child to compensate for wage loss and improve health",
    amount: "₹5,000 in 3 instalments",
    processingTime: "4–8 weeks",
    documents: [
      "Aadhaar card",
      "Bank account linked to Aadhaar",
      "MCP card (Mother & Child Protection)",
      "Proof of pregnancy registration at AWC",
    ],
    deadline: "Register at local Anganwadi Centre (AWC) within first trimester",
    priority: "high",
    tags: ["PMMVY", "cash transfer", "first child"],
    weekToApply: 1,
  },

  {
    id: "in-uip-vaccination",
    country: "IN",
    countryName: "India",
    lifeEvents: ["new-baby"],
    employment: ["any"],
    category: "healthcare",
    name: "Universal Immunisation Programme",
    agency: "Ministry of Health & Family Welfare",
    description: "Free vaccines for children against 12 vaccine-preventable diseases",
    amount: "Free",
    processingTime: "Immediate at government health centre",
    documents: [
      "Birth certificate",
      "Aadhaar (optional at birth)",
    ],
    deadline: "BCG and Hepatitis B within 24 hours of birth",
    priority: "high",
    tags: ["vaccination", "immunisation", "child health"],
    weekToApply: 1,
  },

  {
    id: "in-jsy",
    country: "IN",
    countryName: "India",
    lifeEvents: ["new-baby"],
    employment: ["unemployed", "self-employed"],
    category: "maternity",
    name: "Janani Suraksha Yojana",
    agency: "National Health Mission",
    description: "Cash assistance to promote institutional delivery among poor pregnant women",
    amount: "₹1,400 (rural) / ₹1,000 (urban)",
    processingTime: "Payment at hospital at time of delivery",
    documents: [
      "BPL card or SC/ST certificate",
      "Proof of institutional delivery",
      "Aadhaar card",
      "Bank passbook",
    ],
    deadline: "Apply at hospital at time of delivery",
    priority: "medium",
    tags: ["JSY", "institutional delivery", "cash incentive"],
    weekToApply: 1,
  },

  {
    id: "in-birth-registration",
    country: "IN",
    countryName: "India",
    lifeEvents: ["new-baby"],
    employment: ["any"],
    category: "registration",
    name: "Birth Registration (Civil Registration System)",
    agency: "Local Municipal Authority / Panchayat",
    description: "Mandatory registration of birth — required for all future government services",
    amount: "Free (late fee if after 21 days)",
    processingTime: "1–3 days",
    documents: [
      "Hospital discharge certificate",
      "Parents' Aadhaar cards",
      "Marriage certificate (optional)",
    ],
    deadline: "Within 21 days of birth — mandatory by law",
    priority: "high",
    tags: ["birth certificate", "registration", "mandatory"],
    weekToApply: 1,
  },

  // ═══════════════════ INDIA — JOB LOSS ═══════════════════════

  {
    id: "in-esi-unemployment",
    country: "IN",
    countryName: "India",
    lifeEvents: ["job-loss"],
    employment: ["employed"],
    category: "unemployment",
    name: "ESI Unemployment Allowance",
    agency: "Employees' State Insurance Corporation (ESIC)",
    description: "Unemployment cash benefit for ESIC-covered workers who lose job involuntarily",
    amount: "50% of average daily wages for up to 2 years",
    duration: "Up to 2 years",
    processingTime: "4–6 weeks",
    documents: [
      "ESIC card",
      "Termination letter / Form 5A",
      "Bank account details",
      "Aadhaar card",
    ],
    deadline: "Apply within 90 days of unemployment",
    priority: "high",
    tags: ["ESIC", "unemployment", "benefit"],
    weekToApply: 1,
  },

  {
    id: "in-svanidhi",
    country: "IN",
    countryName: "India",
    lifeEvents: ["job-loss"],
    employment: ["self-employed", "unemployed"],
    category: "loan",
    name: "PM SVANidhi — Street Vendor Loan",
    agency: "Ministry of Housing & Urban Affairs",
    description: "Working capital loan for street vendors to resume livelihood",
    amount: "₹10,000 initial loan (up to ₹50,000 on repayment)",
    processingTime: "7–14 days",
    documents: [
      "Vendor ID card / Certificate of Vending",
      "Aadhaar card",
      "Bank account details",
    ],
    deadline: "Open — apply anytime",
    priority: "medium",
    tags: ["SVANidhi", "vendor", "loan"],
    weekToApply: 2,
  },

  {
    id: "in-ncs-portal",
    country: "IN",
    countryName: "India",
    lifeEvents: ["job-loss"],
    employment: ["any"],
    category: "employment",
    name: "National Career Service (NCS) Portal",
    agency: "Ministry of Labour & Employment",
    description: "Job matching, career counselling, skill development courses, and placement",
    amount: "Free",
    processingTime: "Immediate registration",
    documents: [
      "Aadhaar card",
      "Educational certificates",
    ],
    deadline: "Register immediately after job loss",
    priority: "high",
    tags: ["NCS", "job portal", "career"],
    weekToApply: 1,
  },

  {
    id: "in-pmkvy",
    country: "IN",
    countryName: "India",
    lifeEvents: ["job-loss"],
    employment: ["any"],
    category: "training",
    name: "PMKVY — Free Skill Training",
    agency: "National Skill Development Corporation",
    description: "Free short-term skill training with certification and placement support",
    amount: "Free + ₹500 post-placement support",
    processingTime: "Course-dependent (2–12 weeks)",
    documents: [
      "Aadhaar card",
      "Education certificate",
      "Passport photo",
    ],
    deadline: "Enroll at nearest Skill India Training Centre",
    priority: "medium",
    tags: ["PMKVY", "skill training", "free"],
    weekToApply: 2,
  },

  // ═══════════════════ INDIA — START BUSINESS ═══════════════════════

  {
    id: "in-udyam",
    country: "IN",
    countryName: "India",
    lifeEvents: ["start-business"],
    employment: ["any"],
    category: "registration",
    name: "Udyam Registration (MSME)",
    agency: "Ministry of MSME",
    description: "Official registration for micro, small and medium enterprises — unlocks all MSME benefits",
    amount: "Free",
    processingTime: "Instant (online, self-declaration)",
    documents: [
      "Aadhaar card",
      "PAN card",
      "Bank account details",
    ],
    deadline: "Register before starting operations",
    priority: "high",
    tags: ["Udyam", "MSME", "registration"],
    weekToApply: 1,
  },

  {
    id: "in-gst",
    country: "IN",
    countryName: "India",
    lifeEvents: ["start-business"],
    employment: ["any"],
    category: "registration",
    name: "GST Registration",
    agency: "GST Council / GSTN",
    description: "Mandatory if turnover exceeds ₹40L (₹20L for services). Optional below threshold.",
    amount: "Free",
    processingTime: "3–7 working days",
    documents: [
      "PAN card",
      "Aadhaar card",
      "Bank account statement",
      "Business address proof",
      "Passport photo",
    ],
    deadline: "Within 30 days of crossing threshold or from business start date",
    priority: "high",
    tags: ["GST", "tax", "registration"],
    weekToApply: 1,
  },

  {
    id: "in-startup-india",
    country: "IN",
    countryName: "India",
    lifeEvents: ["start-business"],
    employment: ["any"],
    category: "startup",
    name: "Startup India Recognition",
    agency: "DPIIT / Ministry of Commerce",
    description: "Official startup recognition unlocking tax exemptions, fast-track IPR, and government tender benefits",
    amount: "Tax holiday for 3 years + fee waivers",
    processingTime: "2–3 working days (online)",
    documents: [
      "Certificate of Incorporation / Registration",
      "PAN card",
      "Business description",
      "Innovation proof",
    ],
    deadline: "Apply anytime — within 10 years of incorporation",
    priority: "high",
    tags: ["Startup India", "DPIIT", "tax exemption"],
    weekToApply: 2,
  },

  {
    id: "in-mudra",
    country: "IN",
    countryName: "India",
    lifeEvents: ["start-business"],
    employment: ["self-employed", "unemployed"],
    category: "loan",
    name: "PM MUDRA Loan (Micro Units Development)",
    agency: "MUDRA / Any scheduled bank or NBFC",
    description: "Collateral-free loan for non-farm micro enterprises up to ₹10 lakh",
    amount: "Up to ₹10 lakh (3 tiers: Shishu/Kishore/Tarun)",
    processingTime: "7–14 working days",
    documents: [
      "Business plan",
      "Aadhaar card",
      "PAN card",
      "Last 6 months bank statement",
      "Passport photo",
    ],
    deadline: "Apply at any bank — open scheme",
    priority: "medium",
    tags: ["MUDRA", "loan", "micro enterprise"],
    weekToApply: 2,
  },

  {
    id: "in-trade-license",
    country: "IN",
    countryName: "India",
    lifeEvents: ["start-business"],
    employment: ["any"],
    category: "registration",
    name: "Trade License",
    agency: "Local Municipal Corporation",
    description: "Mandatory license to operate a business within municipal limits",
    amount: "₹1,000 - ₹10,000 (varies by city and business)",
    processingTime: "7–30 days (varies by city)",
    documents: [
      "Identity proof",
      "Address proof",
      "Business premises proof",
      "Property tax receipt",
    ],
    deadline: "Before commencing business operations",
    priority: "high",
    tags: ["trade license", "municipal", "business"],
    weekToApply: 1,
  },

  // ═══════════════════ CALIFORNIA — NEW BABY ═══════════════════════

  {
    id: "ca-pfl",
    country: "CA-US",
    countryName: "California, USA",
    lifeEvents: ["new-baby"],
    employment: ["employed", "self-employed"],
    category: "maternity",
    name: "California Paid Family Leave",
    agency: "CA Employment Development Department (EDD)",
    description: "Wage replacement benefit while bonding with a new child",
    amount: "60–70% of weekly wages (up to $1,620/week)",
    duration: "Up to 8 weeks",
    processingTime: "14–21 days",
    documents: [
      "Social Security Number",
      "Child's birth certificate or hospital records",
      "Employer information",
      "EDD account login",
    ],
    deadline: "File within 41 days of baby's arrival to avoid losing benefits",
    priority: "high",
    tags: ["paid family leave", "PFL", "bonding"],
    weekToApply: 1,
  },

  {
    id: "ca-sdi-pregnancy",
    country: "CA-US",
    countryName: "California, USA",
    lifeEvents: ["new-baby"],
    employment: ["employed"],
    category: "maternity",
    name: "SDI Pregnancy Disability Leave",
    agency: "CA Employment Development Department (EDD)",
    description: "Disability benefits during pregnancy and recovery after birth (for the mother)",
    amount: "60–70% of weekly wages",
    duration: "Up to 4 weeks before birth + 6–8 weeks after (vaginal/C-section)",
    processingTime: "2–3 weeks",
    documents: [
      "EDD online account",
      "Doctor's certification (DE 2501)",
      "Employer information",
    ],
    deadline: "File within 49 days of first day of disability",
    priority: "high",
    tags: ["SDI", "pregnancy", "disability"],
    weekToApply: 1,
  },

  {
    id: "ca-calworks",
    country: "CA-US",
    countryName: "California, USA",
    lifeEvents: ["new-baby"],
    employment: ["unemployed", "self-employed"],
    category: "cash",
    name: "CalWORKs Cash Aid",
    agency: "County Department of Social Services",
    description: "Monthly cash assistance for low-income families with children",
    amount: "$935–$1,396/month (family of 3, varies by county)",
    processingTime: "30–45 days",
    documents: [
      "Proof of identity",
      "Proof of residency",
      "Birth certificates for all children",
      "Proof of income",
      "Social Security cards",
    ],
    deadline: "Apply at county office anytime",
    priority: "medium",
    tags: ["CalWORKs", "cash aid", "family"],
    weekToApply: 2,
  },

  {
    id: "ca-wic",
    country: "CA-US",
    countryName: "California, USA",
    lifeEvents: ["new-baby"],
    employment: ["any"],
    category: "nutrition",
    name: "WIC — Nutrition Program",
    agency: "CA Department of Public Health",
    description: "Free healthy food, formula, breastfeeding support, and health referrals",
    amount: "~$100–200/month in food benefits",
    processingTime: "1–2 weeks",
    documents: [
      "Proof of identity",
      "Proof of California residency",
      "Proof of income",
      "Medical records showing pregnancy or infant age",
    ],
    deadline: "Apply during pregnancy or up to child's 5th birthday",
    priority: "high",
    tags: ["WIC", "nutrition", "food", "infant"],
    weekToApply: 1,
  },

  {
    id: "ca-medicaid-infant",
    country: "CA-US",
    countryName: "California, USA",
    lifeEvents: ["new-baby"],
    employment: ["any"],
    category: "healthcare",
    name: "Medi-Cal (Medicaid) for Newborns",
    agency: "CA Department of Health Care Services",
    description: "Free or low-cost health coverage for newborns in low-to-moderate income families",
    amount: "Free health insurance for the child",
    processingTime: "1–4 weeks",
    documents: [
      "Child's birth certificate",
      "Social Security Number (can apply before SSN is issued)",
      "Proof of household income",
    ],
    deadline: "Apply within 30 days of birth for retroactive coverage from birth date",
    priority: "high",
    tags: ["Medi-Cal", "Medicaid", "infant", "health insurance"],
    weekToApply: 1,
  },

  // ═══════════════════ CALIFORNIA — JOB LOSS ═══════════════════════

  {
    id: "ca-ui",
    country: "CA-US",
    countryName: "California, USA",
    lifeEvents: ["job-loss"],
    employment: ["employed"],
    category: "unemployment",
    name: "Unemployment Insurance",
    agency: "CA Employment Development Department (EDD)",
    description: "Weekly payments while you search for work after involuntary job loss",
    amount: "$40–$450/week (based on prior earnings)",
    duration: "Up to 26 weeks",
    processingTime: "3–5 weeks for first payment",
    documents: [
      "Social Security Number",
      "Last employer's name, address, phone",
      "Dates of employment",
      "Reason for separation",
      "Wage information (pay stubs)",
    ],
    deadline: "File within 3 weeks of job loss to avoid losing benefits",
    priority: "high",
    tags: ["unemployment insurance", "EDD", "UI"],
    weekToApply: 1,
  },

  {
    id: "ca-calfresh",
    country: "CA-US",
    countryName: "California, USA",
    lifeEvents: ["job-loss"],
    employment: ["any"],
    category: "nutrition",
    name: "CalFresh Food Benefits",
    agency: "CA Department of Social Services",
    description: "Monthly electronic benefits to buy groceries at most stores",
    amount: "$23–$250+/month depending on household size",
    processingTime: "3 days (emergency) to 30 days",
    documents: [
      "Proof of identity",
      "Proof of address",
      "Proof of income (or lack thereof)",
      "Social Security Number",
    ],
    deadline: "Apply anytime — benefits can start within 3 days for emergency cases",
    priority: "high",
    tags: ["CalFresh", "SNAP", "food stamps", "groceries"],
    weekToApply: 1,
  },

  {
    id: "ca-medicaid-jobloss",
    country: "CA-US",
    countryName: "California, USA",
    lifeEvents: ["job-loss"],
    employment: ["any"],
    category: "healthcare",
    name: "Medi-Cal Health Coverage",
    agency: "Covered California / DHCS",
    description: "Free or low-cost health insurance after losing employer coverage",
    amount: "Free for incomes below 138% FPL",
    processingTime: "1–4 weeks",
    documents: [
      "Proof of identity",
      "Proof of income (or unemployment confirmation)",
      "Social Security Number",
    ],
    deadline: "Job loss = qualifying life event — apply within 60 days",
    priority: "high",
    tags: ["Medi-Cal", "health insurance", "job loss"],
    weekToApply: 1,
  },

  {
    id: "ca-edd-jobs",
    country: "CA-US",
    countryName: "California, USA",
    lifeEvents: ["job-loss"],
    employment: ["any"],
    category: "employment",
    name: "America's Job Center of California",
    agency: "CA EDD / Labor & Workforce Development",
    description: "Free job placement, resume help, interview coaching, and skills workshops",
    amount: "Free",
    processingTime: "Immediate",
    documents: [
      "Government ID",
      "Resume",
    ],
    deadline: "Register immediately — required to maintain UI benefits",
    priority: "high",
    tags: ["job center", "placement", "resume"],
    weekToApply: 1,
  },

  // ═══════════════════ CALIFORNIA — START BUSINESS ═══════════════════════

  {
    id: "ca-biz-registration",
    country: "CA-US",
    countryName: "California, USA",
    lifeEvents: ["start-business"],
    employment: ["any"],
    category: "registration",
    name: "Business Entity Registration",
    agency: "CA Secretary of State",
    description: "Register your LLC, Corporation, or Partnership with the state of California",
    amount: "$70 (LLC) / $100 (Corporation) filing fee",
    processingTime: "3–5 business days (online)",
    documents: [
      "Articles of Organization/Incorporation",
      "Registered Agent information",
      "Business address",
    ],
    deadline: "Before conducting business in CA",
    priority: "high",
    tags: ["LLC", "corporation", "Secretary of State"],
    weekToApply: 1,
  },

  {
    id: "ca-sellers-permit",
    country: "CA-US",
    countryName: "California, USA",
    lifeEvents: ["start-business"],
    employment: ["any"],
    category: "registration",
    name: "Seller's Permit",
    agency: "CA Department of Tax & Fee Administration (CDTFA)",
    description: "Required if you sell tangible goods in California — allows you to collect sales tax",
    amount: "Free",
    processingTime: "Instant (online)",
    documents: [
      "SSN or ITIN",
      "Business address",
      "Bank account information",
      "Estimated monthly sales",
    ],
    deadline: "Before first sale",
    priority: "high",
    tags: ["seller's permit", "sales tax", "CDTFA"],
    weekToApply: 1,
  },

  {
    id: "ca-ein",
    country: "CA-US",
    countryName: "California, USA",
    lifeEvents: ["start-business"],
    employment: ["any"],
    category: "registration",
    name: "Federal EIN (Tax ID)",
    agency: "IRS",
    description: "Federal tax identification number — required to open business bank account, hire employees, and file taxes",
    amount: "Free",
    processingTime: "Instant (IRS online)",
    documents: [
      "SSN or ITIN",
      "Business legal name",
      "Business structure type",
    ],
    deadline: "Apply before opening bank account or hiring employees",
    priority: "high",
    tags: ["EIN", "tax ID", "IRS"],
    weekToApply: 1,
  },

  {
    id: "ca-osba-grants",
    country: "CA-US",
    countryName: "California, USA",
    lifeEvents: ["start-business"],
    employment: ["any"],
    category: "grant",
    name: "CA Small Business & Nonprofit Relief Grants",
    agency: "CA Office of the Small Business Advocate (CalOSBA)",
    description: "State-administered grants for small businesses — multiple rounds throughout year",
    amount: "$5,000–$25,000",
    processingTime: "4–8 weeks after window closes",
    documents: [
      "Business registration docs",
      "Tax returns (last 2 years)",
      "Proof of revenue impact",
      "Business bank statements",
    ],
    deadline: "Grant windows open periodically — sign up for notifications at business.ca.gov",
    priority: "medium",
    tags: ["grant", "CalOSBA", "small business"],
    weekToApply: 4,
  },

  {
    id: "ca-city-license",
    country: "CA-US",
    countryName: "California, USA",
    lifeEvents: ["start-business"],
    employment: ["any"],
    category: "registration",
    name: "City Business License",
    agency: "Local City/County Clerk's Office",
    description: "Local operating permit required by most California cities and counties",
    amount: "$50–$500/year (varies by city and revenue)",
    processingTime: "1–5 business days",
    documents: [
      "State business registration",
      "Business address",
      "Business type description",
    ],
    deadline: "Within 30 days of starting operations",
    priority: "high",
    tags: ["business license", "city", "local permit"],
    weekToApply: 1,
  },
];

// ── Helpers ────────────────────────────────────────────────────────────────

export type LifeEvent = "new-baby" | "job-loss" | "start-business";
export type Employment = "employed" | "self-employed" | "unemployed";
export type Country = "IE" | "UAE" | "RW" | "IN" | "CA-US";

export function filterServices(
  lifeEvent: LifeEvent,
  employment: Employment,
  country: Country
): GovernmentService[] {
  return services
    .filter(
      (s) =>
        s.country === country &&
        s.lifeEvents.includes(lifeEvent) &&
        (s.employment.includes("any") || s.employment.includes(employment))
    )
    .sort((a, b) => {
      const priorityOrder = { high: 0, medium: 1, low: 2 };
      if (priorityOrder[a.priority] !== priorityOrder[b.priority])
        return priorityOrder[a.priority] - priorityOrder[b.priority];
      return a.weekToApply - b.weekToApply;
    });
}

export function getAssumptions(
  lifeEvent: LifeEvent,
  employment: Employment,
  country: Country
): string[] {
  const countryNames: Record<Country, string> = { IE: "Ireland", UAE: "UAE", RW: "Rwanda", IN: "India", "CA-US": "California" };
  const employmentLabels: Record<Employment, string> = {
    employed: "Employed",
    "self-employed": "Self-employed",
    unemployed: "Unemployed",
  };
  return [
    `You are based in ${countryNames[country]}`,
    `You are ${employmentLabels[employment].toLowerCase()}`,
  ];
}

export function getRefinements(
  lifeEvent: LifeEvent,
  employment: Employment
): string[] {
  const refs: Record<string, string[]> = {
    "new-baby-employed":          ["I'm self-employed", "I'm unemployed"],
    "new-baby-self-employed":     ["I'm employed", "I'm unemployed"],
    "new-baby-unemployed":        ["I'm employed", "I'm self-employed"],
    "job-loss-unemployed":        ["I was self-employed"],
    "job-loss-employed":          ["I'm unemployed", "I'm self-employed"],
    "job-loss-self-employed":     ["I'm unemployed", "I'm employed"],
    "start-business-employed":    ["I'm currently unemployed", "I'm already self-employed"],
    "start-business-unemployed":  ["I'm currently employed", "I'm already self-employed"],
    "start-business-self-employed": ["I'm currently employed", "I'm currently unemployed"],
  };
  return refs[`${lifeEvent}-${employment}`] ?? [];
}

export function getServicesByCountry(country: Country): GovernmentService[] {
  const allServices: GovernmentService[] = [];
  const lifeEvents: LifeEvent[] = ["new-baby", "job-loss", "start-business"];
  const employments: Employment[] = ["employed", "unemployed", "self-employed"];
  const seen = new Set<string>();
  for (const le of lifeEvents) {
    for (const emp of employments) {
      const svcs = filterServices(le, emp, country);
      for (const s of svcs) {
        if (!seen.has(s.id)) {
          seen.add(s.id);
          allServices.push(s);
        }
      }
    }
  }
  return allServices;
}

export function estimateTotalValue(filtered: GovernmentService[]): string {
  let total = 0;
  for (const s of filtered) {
    if (!s.amount) continue;
    const a = s.amount;
    // €250/week × 26 weeks
    if (a.includes("/week") && s.duration) {
      const weekly = parseFloat(a.replace(/[^0-9.]/g, ""));
      const weeks = parseFloat((s.duration.match(/(\d+)\s*week/) ?? [])[1] ?? "0");
      if (!isNaN(weekly) && weeks > 0) total += weekly * weeks;
    }
    // €140/month → 12 months
    else if (a.includes("/month")) {
      const monthly = parseFloat(a.replace(/[^0-9.]/g, ""));
      if (!isNaN(monthly)) total += monthly * 12;
    }
    // Fixed amounts like €150,000
    else if (a.startsWith("€") || a.startsWith("Up to €")) {
      const amount = parseFloat(a.replace(/[^0-9.]/g, ""));
      if (!isNaN(amount) && amount < 200000) total += amount * 0.15; // conservative 15% of max
    }
  }
  if (total === 0) return "Significant value";
  if (total >= 1000) return `€${Math.round(total / 1000)}k+`;
  return `€${Math.round(total)}+`;
}
